"""add_license_provenance

Revision ID: 3e3eccf9015e
Revises: 99c37ef7c43c
Create Date: 2026-02-14 18:45:53.314742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3eccf9015e'
down_revision: Union[str, None] = '99c37ef7c43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_rulesets', sa.Column('license_type', sa.String(), nullable=False, server_default='PROPRIETARY', comment="License identifier, e.g. 'CC-BY-4.0', 'OGL-1.0a', 'PROPRIETARY'."))
    op.add_column('official_rulesets', sa.Column('source_url', sa.String(), nullable=True, comment='URL where the open-licensed content was fetched from.'))
    op.add_column('official_rulesets', sa.Column('attribution_text', sa.Text(), nullable=True, comment='Required attribution notice for CC/OGL content.'))
    op.add_column('official_rulesets', sa.Column('is_crawlable', sa.Boolean(), nullable=False, server_default='false', comment='Whether we can legally auto-fetch and index the rules content.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('official_rulesets', 'is_crawlable')
    op.drop_column('official_rulesets', 'attribution_text')
    op.drop_column('official_rulesets', 'source_url')
    op.drop_column('official_rulesets', 'license_type')
    # ### end Alembic commands ###
