"""add_subscription_tiers

Revision ID: 4fc7b20cadfa
Revises: 053437c609a1
Create Date: 2026-02-14 15:26:03.895251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc7b20cadfa'
down_revision: Union[str, None] = '053437c609a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('daily_query_limit', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_tiers_name'), 'subscription_tiers', ['name'], unique=True)
    # ### end Alembic commands ###

    # Seed data
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer, DateTime
    from sqlalchemy import func
    import uuid

    from datetime import datetime, timezone
    from sqlalchemy.dialects.postgresql import UUID

    subscription_tiers = table('subscription_tiers',
        column('id', UUID(as_uuid=True)), 
        column('name', String),
        column('daily_query_limit', Integer),
        column('created_at', DateTime(timezone=True)),
        column('updated_at', DateTime(timezone=True))
    )

    now = datetime.now(timezone.utc)

    op.bulk_insert(subscription_tiers,
        [
            {
                'id': str(uuid.uuid4()),
                'name': 'FREE',
                'daily_query_limit': 5,
                'created_at': now,
                'updated_at': now
            },
            {
                'id': str(uuid.uuid4()),
                'name': 'PRO',
                'daily_query_limit': -1,
                'created_at': now,
                'updated_at': now
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_tiers_name'), table_name='subscription_tiers')
    op.drop_table('subscription_tiers')
    # ### end Alembic commands ###
