"""add publisher_display_name to official_rulesets

Revision ID: 99c37ef7c43c
Revises: b51cd47aae46
Create Date: 2026-02-14 18:40:03.057434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99c37ef7c43c'
down_revision: Union[str, None] = 'b51cd47aae46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_rulesets', sa.Column('publisher_display_name', sa.String(), nullable=True, comment="Actual game publisher (e.g. 'Wizards of the Coast'). Falls back to Publisher.name if null."))
    op.alter_column('party_game_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('party_game_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('official_rulesets', 'publisher_display_name')
    # ### end Alembic commands ###
