"""initial schema - all 8 tables

Revision ID: a6983e1c5e84
Revises: 
Create Date: 2026-02-14 13:41:59.761374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6983e1c5e84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('tier_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('file_blocklist',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('official_rulesets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('game_slug', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_priority', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pinecone_namespace', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_rulesets_game_slug'), 'official_rulesets', ['game_slug'], unique=False)
    op.create_index(op.f('ix_official_rulesets_publisher_id'), 'official_rulesets', ['publisher_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('active_ruleset_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_game_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('official_ruleset_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('personal_ruleset_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('last_queried', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_game_library_user_id'), 'user_game_library', ['user_id'], unique=False)
    op.create_table('query_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('expanded_query', sa.Text(), nullable=True),
    sa.Column('verdict_summary', sa.Text(), nullable=True),
    sa.Column('reasoning_chain', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('citation_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_audit_log_created_at'), 'query_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_audit_log_session_id'), 'query_audit_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_query_audit_log_user_id'), 'query_audit_log', ['user_id'], unique=False)
    op.create_table('ruleset_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_priority', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruleset_metadata_session_id'), 'ruleset_metadata', ['session_id'], unique=False)
    op.create_index(op.f('ix_ruleset_metadata_status'), 'ruleset_metadata', ['status'], unique=False)
    op.create_index(op.f('ix_ruleset_metadata_user_id'), 'ruleset_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ruleset_metadata_user_id'), table_name='ruleset_metadata')
    op.drop_index(op.f('ix_ruleset_metadata_status'), table_name='ruleset_metadata')
    op.drop_index(op.f('ix_ruleset_metadata_session_id'), table_name='ruleset_metadata')
    op.drop_table('ruleset_metadata')
    op.drop_index(op.f('ix_query_audit_log_user_id'), table_name='query_audit_log')
    op.drop_index(op.f('ix_query_audit_log_session_id'), table_name='query_audit_log')
    op.drop_index(op.f('ix_query_audit_log_created_at'), table_name='query_audit_log')
    op.drop_table('query_audit_log')
    op.drop_index(op.f('ix_user_game_library_user_id'), table_name='user_game_library')
    op.drop_table('user_game_library')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_official_rulesets_publisher_id'), table_name='official_rulesets')
    op.drop_index(op.f('ix_official_rulesets_game_slug'), table_name='official_rulesets')
    op.drop_table('official_rulesets')
    op.drop_table('file_blocklist')
    op.drop_table('users')
    op.drop_table('publishers')
    # ### end Alembic commands ###
